create extension if not exists pgcrypto;

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  sku text not null default '',
  category text not null default 'عام',
  unit text not null default 'حبة',
  price numeric(12,2) not null default 0 check (price >= 0),
  min_price numeric(12,2) not null default 0 check (min_price >= 0),
  description text not null default '',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.site_settings (
  id integer primary key default 1 check (id = 1),
  instagram_url text not null default '',
  tiktok_url text not null default '',
  tax_rate numeric(5,2) not null default 15,
  logo_url text not null default '',
  updated_at timestamptz not null default now()
);

insert into public.site_settings (id) values (1)
on conflict (id) do nothing;

create table if not exists public.quotes (
  id uuid primary key default gen_random_uuid(),
  quote_no bigint generated by default as identity,
  customer_name text not null default 'عميل نقدي',
  customer_phone text not null default '',
  tax_enabled boolean not null default false,
  tax_rate numeric(5,2) not null default 15,
  discount numeric(12,2) not null default 0,
  notes text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.quote_items (
  id uuid primary key default gen_random_uuid(),
  quote_id uuid not null references public.quotes(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  item_name text not null,
  sku text not null default '',
  unit text not null default 'حبة',
  qty numeric(12,2) not null check (qty > 0),
  price numeric(12,2) not null check (price >= 0),
  created_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_users
    where user_id = auth.uid()
  );
$$;

alter table public.admin_users enable row level security;
alter table public.products enable row level security;
alter table public.site_settings enable row level security;
alter table public.quotes enable row level security;
alter table public.quote_items enable row level security;

create policy "admin users can view admins"
on public.admin_users for select
using (public.is_admin());

create policy "public can view active products"
on public.products for select
using (active = true or public.is_admin());

create policy "admins manage products"
on public.products for all
using (public.is_admin())
with check (public.is_admin());

create policy "public can read settings"
on public.site_settings for select
using (true);

create policy "admins update settings"
on public.site_settings for update
using (public.is_admin())
with check (public.is_admin());

create policy "public can create quotes"
on public.quotes for insert
with check (true);

create policy "admins view and manage quotes"
on public.quotes for all
using (public.is_admin())
with check (public.is_admin());

create policy "public can add quote items"
on public.quote_items for insert
with check (
  exists (select 1 from public.quotes q where q.id = quote_id)
);

create policy "admins view and manage quote items"
on public.quote_items for all
using (public.is_admin())
with check (public.is_admin());

create or replace function public.check_quote_item_price()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  minimum numeric(12,2);
begin
  if new.product_id is not null then
    select min_price into minimum
    from public.products
    where id = new.product_id;

    if minimum is not null and new.price < minimum then
      raise exception 'السعر أقل من الحد الأدنى المسموح';
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists quote_item_min_price on public.quote_items;
create trigger quote_item_min_price
before insert or update on public.quote_items
for each row execute function public.check_quote_item_price();
